#!/usr/bin/env python

"""Trac Search

Usage:
    tracsearch delete [--config FILE]
    tracsearch ticket [--config FILE]
    tracsearch wiki [--config FILE]
    tracsearch web [--config FILE]

Option:
    --config FILE Config file.
"""
import datetime

from docopt import docopt

from tracsearch.config import config
from tracsearch.trac import Trac
from tracsearch.search import TracSearch, datetimeformat
from tracsearch.web import run


arguments = docopt(__doc__, version='Trac search 0.5')

if arguments['--config'] is None:
    config.read(['tracsearch.ini'])
else:
    config.read([arguments['--config']])

search = TracSearch(
    config.get('elasticsearch', 'url', 'http://127.0.0.1:9200'),
    bulk_size=config.getint('elasticsearch', 'bulk_size')
)

if arguments['delete']:
    search.recreate()
elif arguments['ticket']:
    for t in config.tracs():
        trac = Trac(config.get(t, 'url', None))

        period = datetime.timedelta(config.getint(t, 'ticket_timedelta'))

        for ticket, comments in trac.ticket(period):
            print ticket['title']
            ticket['comment'] = []
            ticket['changetime'] = datetimeformat(ticket['changetime'])
            n = 0
            for comment in comments:
                comment['id'] = "%s_%i" % (ticket['id'], n)
                ticket['comment'].append(comment)
                n += 1
            search.index('ticket', ticket, bulk=True)

        search.flush_bulk('ticket')
elif arguments['wiki']:
    for t in config.tracs():
        trac = Trac(config.get(t, 'url', None))

        for wiki in trac.wiki():
            print wiki['title']
            wiki['changetime'] = datetimeformat(wiki['lastModified'])
            search.index('wiki', wiki, bulk=True)

        search.flush_bulk('wiki')
elif arguments['web']:
    run(config)
