#!/usr/bin/env python

"""Trac Search

Usage:
    tracsearch delete [--config FILE]
    tracsearch ticket [--config FILE]
    tracsearch wiki [--config FILE]
    tracsearch web [--config FILE]

Option:
    --config FILE Config file.
"""
import datetime

from docopt import docopt

from tracsearch.config import config
from tracsearch.trac import Trac
from tracsearch.search import TracSearch, datetimeformat
from tracsearch.web import run
from elasticsearch import Elasticsearch


arguments = docopt(__doc__, version='Trac search 0.5')

if arguments['--config'] is None:
    config.read(['tracsearch.ini'])
else:
    config.read([arguments['--config']])

search = TracSearch(
    Elasticsearch(config.get('elasticsearch', 'url', '127.0.0.1:9200'))
)

assert search.ping()

if arguments['delete']:
    search.purge()
    search.prepare_indices()
    search.refresh()

elif arguments['ticket']:
    for t in config.tracs():
        trac = Trac(config.get(t, 'url', None))

        period = datetime.timedelta(config.getint(t, 'ticket_timedelta'))

        def ticket_factory():
            for ticket, comments in trac.ticket(period):
                print ticket['title']
                ticket['comment'] = []
                ticket['changetime'] = datetimeformat(ticket['changetime'])
                n = 0
                for comment in comments:
                    comment['id'] = "%s_%i" % (ticket['id'], n)
                    ticket['comment'].append(comment)
                    n += 1
                yield ticket

        search.index('ticket', ticket_factory())
        search.refresh()

elif arguments['wiki']:
    def wiki_factory():
        for t in config.tracs():
            trac = Trac(config.get(t, 'url', None))

            for wiki in trac.wiki():
                print wiki['title']
                wiki['changetime'] = datetimeformat(wiki['lastModified'])
                yield wiki
    search.index('wiki', wiki_factory())
    search.refresh()

elif arguments['web']:
    run(config)
